Ignore changes to engine_version
byu-oit/terraform-aws-rds pull request #14
Opened 2020-10-26 21:48 UTC by GaryGSC

Since [`auto_minor_version_upgrade` defaults to `true`](https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/latest#inputs), we're allowing AWS to update `engine_version` without a corresponding change in our Terraform files.

This resulted in an error during one of our deployments because we declared engine version 11.6: [`Error modifying DB Instance ces-adm-sd-uapp-prd: InvalidParameterCombination: Cannot upgrade postgres from 11.8 to 11.6`](https://github.com/byu-oit/ces-adm-sd-uapp/runs/1311287132?check_suite_focus=true#step:15:19)

Ignoring changes to `engine_version` would allow us to avoid these errors in the future. It would also make it harder for developers to accidentally destroy data.

2020-10-26 21:51 UTC, GaryGSC commented
I think CI is broken due to some unrelated IAM issues.

2020-10-27 01:19 UTC, jvisker commented
The CI is broken because @joshgubler and I were messing around with a proof of concept.

2020-10-27 01:20 UTC, jvisker commented
I'm hesitant to add an `'ignore_changes` flag. I just worry that it will make things more confusing for people in a different way.

2020-10-27 15:05 UTC, GaryGSC commented
That's a reasonable concern. `ignore_changes` blocks can be unexpected. I could imagine a developer trying to update a major version and being confused as to why nothing's happening.

2020-11-17 17:10 UTC, blakemorgan reviewed
I'm in the "approve" boat. I think all we need is a note about updating a major version and keep the `ignore_changes` because minor version updates are more frequent.

2021-06-08 19:10 UTC, stuft2 requested changes
We'll need to update the example and README again but LGTM.

2021-06-08 22:51 UTC, GaryGSC commented
Once #24 is merged, I'll rebase this one and update the PR to call it `v2.3.3`.

2021-06-15 15:06 UTC, stuft2 commented
> Once #24 is merged, I'll rebase this one and update the PR to call it `v2.3.3`.

Merged 👍🏻

2022-10-21 22:55 UTC, stuft2 commented
A conversation with @whyriod today got me thinking about this PR again: https://teams.microsoft.com/l/message/19:3c7a67b78429456da1aee7b57dd8a05f@thread.tacv2/1666365637472?tenantId=c6fc6e9b-51fb-48a8-b779-9ee564b40413&groupId=d521e695-6316-4c7c-a824-26936ea2bd17&parentMessageId=1666365637472&teamName=Guilds&channelName=Cloud&createdTime=1666365637472&allowXTenantAccess=false

2022-10-24 14:05 UTC, stuft2 commented
Closing in favor of https://github.com/byu-oit/terraform-aws-rds/pull/26

2022-10-24 14:05 UTC, closed without merging